import { useCallback, useEffect, useMemo, useState } from 'react'
import { LoaderCircle, MapPin, RefreshCw, ShieldCheck, X } from 'lucide-react'
import { actionLabels, resolutionTypes } from '../data/caseOptions'

const tabs = ['Overview', 'Grievance', 'Satellite Analysis', 'Priority', 'Inspections', 'Evidence', 'Admin Review', 'Timeline']
const newKey = () => globalThis.crypto?.randomUUID?.().replaceAll('-', '') || `caseaction${Date.now()}`

const Field = ({ label, value }) => <p><span className="block text-[8px] font-bold uppercase tracking-wider text-ink/40">{label}</span><strong className="mt-0.5 block text-[10px]">{value ?? 'Not available'}</strong></p>

const EvidenceGrid = ({ items, onOpen }) => items?.length ? <div className="grid grid-cols-3 gap-2">{items.map((item) => <button key={item.evidence_id} onClick={() => onOpen(item)} className="overflow-hidden rounded-lg border border-ink/10"><img src={item.url} alt={item.file_name} className="aspect-square w-full object-cover" /><span className="block truncate p-1 text-[8px]">{item.file_name}</span></button>)}</div> : <p className="text-[10px] text-ink/50">No image evidence is available.</p>

export default function CaseDetail({ caseId, onClose, onChanged, onOpenParcel, onStartInspection }) {
  const [detail, setDetail] = useState(null)
  const [loadError, setLoadError] = useState('')
  const [tab, setTab] = useState('Overview')
  const [note, setNote] = useState('')
  const [resolutionType, setResolutionType] = useState('')
  const [submitting, setSubmitting] = useState('')
  const [actionError, setActionError] = useState('')
  const [success, setSuccess] = useState('')
  const [lightbox, setLightbox] = useState(null)
  const load = useCallback(() => {
    setLoadError('')
    fetch(`/api/cases/${encodeURIComponent(caseId)}`)
      .then((response) => response.ok ? response.json() : Promise.reject())
      .then(setDetail)
      .catch(() => setLoadError('Administrative case could not be loaded. Ensure the local backend is running.'))
  }, [caseId])
  useEffect(() => { load() }, [load])
  const allEvidence = useMemo(() => detail ? [
    ...(detail.grievance.evidence || []),
    ...detail.inspections.flatMap((inspection) => inspection.evidence || []),
  ] : [], [detail])
  const submit = async (endpoint, payload, label) => {
    if (submitting) return
    setSuccess('')
    if (note.trim().length < 10 || note.trim().length > 3000) { setActionError('Administrative note must contain 10–3000 characters.'); return }
    if (payload.action === 'resolve_case' && !resolutionType) { setActionError('Choose a resolution type.'); return }
    setSubmitting(label); setActionError('')
    try {
      const response = await fetch(`/api/cases/${encodeURIComponent(caseId)}/${endpoint}`, {
        method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Idempotency-Key': newKey() },
        body: JSON.stringify(payload.action ? { ...payload, note: note.trim(), resolution_type: payload.action === 'resolve_case' ? resolutionType : null } : { review_note: note.trim() }),
      })
      const body = await response.json()
      if (!response.ok) throw new Error(body.detail?.message || 'Administrative action could not be recorded.')
      setNote(''); setResolutionType(''); setSuccess(body.message); load(); onChanged?.()
    } catch (error) { setActionError(error.message || 'Administrative action could not be recorded.') }
    finally { setSubmitting('') }
  }
  if (loadError) return <div className="fixed inset-0 z-[90] grid place-items-center bg-black/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5"><p role="alert" className="text-sm text-rose-800">{loadError}</p><div className="mt-4 flex gap-2"><button onClick={load} className="rounded-xl bg-ink px-4 py-2 text-xs font-bold text-white">Retry</button><button onClick={onClose} className="rounded-xl border px-4 py-2 text-xs font-bold">Close</button></div></div></div>
  if (!detail) return <div className="fixed inset-0 z-[90] grid place-items-center bg-black/60"><span className="flex items-center gap-2 rounded-xl bg-white p-4 text-xs"><LoaderCircle className="animate-spin" size={16} /> Loading administrative case…</span></div>
  const section = {
    Overview: <div className="space-y-3"><div className="grid grid-cols-2 gap-3 rounded-xl bg-sand/65 p-3 sm:grid-cols-4"><Field label="Status" value={detail.case_status} /><Field label="Review stage" value={detail.review_stage} /><Field label="Opened" value={new Date(detail.opened_at).toLocaleString()} /><Field label="Updated" value={new Date(detail.updated_at).toLocaleString()} /><Field label="Parcel" value={detail.parcel_id} /><Field label="Survey" value={detail.survey_number} /><Field label="Village / Taluka" value={`${detail.village} · ${detail.taluka}`} /><Field label="Priority" value={`${detail.latest_priority_score} · ${detail.latest_priority_level}`} /></div><div className="grid gap-2 sm:grid-cols-2"><div className="rounded-xl border p-3 text-[10px]"><strong>Linked grievance</strong><p className="mt-1">{detail.grievance.category}</p><p className="mt-1 text-ink/50">{detail.grievance.description}</p></div><div className="rounded-xl border p-3 text-[10px]"><strong>Evidence context</strong><p className="mt-1">Satellite change: {detail.satellite_analysis ? `${detail.satellite_analysis.change_percentage}%` : 'No analysis'}</p><p>Inspections: {detail.inspection_count}</p><p>Grievance images: {detail.grievance_evidence_count}</p><p>Inspection images: {detail.inspection_evidence_count}</p></div></div><div className="grid gap-2 sm:grid-cols-2"><p className="rounded-xl bg-amber-50 p-3 text-[10px] text-amber-900">Field verification: {detail.requires_field_verification ? 'Required' : 'Not requested'}</p><p className="rounded-xl bg-blue-50 p-3 text-[10px] text-blue-900">More information: {detail.requires_more_information ? 'Required' : 'Not requested'}</p></div></div>,
    Grievance: <div className="space-y-3"><div className="rounded-xl bg-sand/65 p-3"><div className="grid grid-cols-2 gap-3"><Field label="Reference" value={detail.grievance.grievance_id} /><Field label="Status" value={detail.grievance.status} /><Field label="Category" value={detail.grievance.category} /><Field label="Submitted" value={new Date(detail.grievance.submitted_at).toLocaleString()} /></div><p className="mt-3 border-t border-ink/10 pt-3 text-xs">{detail.grievance.description}</p></div><EvidenceGrid items={detail.grievance.evidence} onOpen={setLightbox} /><p className="rounded-xl bg-blue-50 p-3 text-[10px] text-blue-900">Citizen-submitted information requires official verification and cannot be edited here.</p></div>,
    'Satellite Analysis': detail.satellite_analysis ? <div className="space-y-3"><img src={detail.satellite_analysis.overlay_url} alt="Change-analysis overlay" className="w-full rounded-xl border object-cover" /><div className="grid grid-cols-3 gap-2"><Field label="Change" value={`${detail.satellite_analysis.change_percentage}%`} /><Field label="Changed area" value={`${detail.satellite_analysis.changed_area_sqm} m²`} /><Field label="Status" value={detail.satellite_analysis.change_status} /></div><p className="rounded-xl bg-amber-50 p-3 text-[10px] text-amber-900">{detail.satellite_analysis.legal_notice}</p></div> : <p className="rounded-xl bg-sand/65 p-4 text-xs text-ink/55">No satellite analysis is available for this synthetic parcel.</p>,
    Priority: <div className="space-y-3"><div className="rounded-xl bg-ink p-4 text-white"><p className="text-[9px] uppercase tracking-wider text-lime">Inspection Priority</p><p className="mt-1 font-display text-3xl font-extrabold">{detail.priority.priority_score} <span className="text-sm">/ 100</span></p><p className="text-xs text-white/70">{detail.priority.priority_level}</p></div>{detail.priority.factors.map((factor) => <div key={factor.factor} className="rounded-xl border p-3 text-[10px]"><strong>{factor.factor}: {factor.points} / {factor.max_points}</strong><p className="mt-1 text-ink/50">{factor.reason}</p></div>)}<p className="text-[10px] text-ink/50">{detail.priority.recommendation} · {detail.priority.score_version}</p></div>,
    Inspections: detail.inspections.length ? <div className="space-y-2">{detail.inspections.map((inspection) => <article key={inspection.inspection_id} className="rounded-xl border p-3 text-[10px]"><strong>{inspection.inspection_id} · {inspection.inspection_outcome}</strong><p className="mt-1 text-ink/55">{inspection.observations}</p><p className="mt-1">Location: {inspection.location ? `${inspection.location.latitude}, ${inspection.location.longitude}` : 'Unavailable'} · Evidence: {inspection.evidence_count}</p></article>)}</div> : <p className="rounded-xl bg-sand/65 p-4 text-xs text-ink/55">No field inspection has been completed for this parcel.</p>,
    Evidence: <EvidenceGrid items={allEvidence} onOpen={setLightbox} />,
    'Admin Review': <div className="space-y-3"><div className="rounded-xl border border-violet-200 bg-violet-50 p-3 text-[10px] text-violet-950"><strong className="flex items-center gap-2"><ShieldCheck size={14} /> Demo Administrative Session</strong><p className="mt-1">{detail.demo_session.actor_display} · {detail.demo_session.actor_reference}</p></div>{detail.administrative_summary && <p className="rounded-xl bg-sand/65 p-3 text-[10px]"><strong>Latest administrative summary:</strong><br />{detail.administrative_summary}</p>}<label className="block text-[10px] font-bold">Administrative note<textarea aria-label="Administrative note" value={note} onChange={(event) => setNote(event.target.value)} maxLength={3000} className="mt-1 min-h-28 w-full rounded-xl border border-ink/15 p-3 text-xs font-normal" placeholder="Record the reason for this review action…" /></label>{detail.allowed_actions.includes('resolve_case') && <label className="block text-[10px] font-bold">Resolution type<select aria-label="Resolution type" value={resolutionType} onChange={(event) => setResolutionType(event.target.value)} className="mt-1 h-11 w-full rounded-xl border border-ink/15 px-3 text-xs font-normal"><option value="">Choose resolution type…</option>{resolutionTypes.map((value) => <option key={value}>{value}</option>)}</select></label>}{actionError && <p role="alert" className="rounded-xl bg-rose-50 p-3 text-[10px] text-rose-800">{actionError}</p>}{success && <p role="status" className="rounded-xl bg-emerald-50 p-3 text-[10px] text-emerald-800">{success}</p>}<div className="grid gap-2 sm:grid-cols-2"><button onClick={() => submit('notes', {}, 'note')} disabled={Boolean(submitting) || detail.case_status === 'Closed'} className="rounded-xl border border-ink/15 px-3 py-3 text-[10px] font-bold disabled:opacity-40">{submitting === 'note' ? 'Saving note…' : 'Add Review Note'}</button>{detail.allowed_actions.map((action) => <button key={action} onClick={() => submit('actions', { action }, action)} disabled={Boolean(submitting)} className="rounded-xl bg-ink px-3 py-3 text-[10px] font-bold text-white disabled:opacity-40">{submitting === action ? 'Recording…' : actionLabels[action]}</button>)}</div>{detail.case_status === 'Closed' && <p className="text-[10px] text-ink/50">Closed cases are read-only.</p>}</div>,
    Timeline: <div className="space-y-2">{detail.events.map((event) => <article key={event.event_id} className="relative rounded-xl border border-ink/10 p-3 pl-8 text-[10px]"><span className="absolute left-3 top-4 h-2 w-2 rounded-full bg-moss" /><strong className="uppercase tracking-wider">{event.event_type}</strong><p className="mt-1 text-ink/55">{new Date(event.created_at).toLocaleString()} · {event.actor_display}</p><p className="mt-1">{event.note}</p>{event.from_status && <p className="mt-1 text-[9px] text-ink/45">{event.from_status} → {event.to_status} · {event.from_stage} → {event.to_stage}</p>}</article>)}</div>,
  }[tab]
  return <div className="fixed inset-0 z-[90] flex items-end justify-center bg-black/60 p-0 sm:items-center sm:p-4" role="dialog" aria-label="Administrative case detail"><div className="flex max-h-[96vh] w-full max-w-5xl flex-col overflow-hidden rounded-t-2xl bg-white shadow-2xl sm:rounded-2xl"><header className="flex items-start justify-between bg-ink p-4 text-white"><div><p className="text-[9px] font-extrabold uppercase tracking-widest text-lime">Administrative Case · Demo</p><h2 className="mt-1 font-display text-xl font-extrabold">{detail.case_id}</h2><p className="text-[10px] text-white/55">{detail.grievance_id} · {detail.parcel_id} · {detail.case_status}</p></div><button onClick={onClose} className="rounded-xl bg-white/10 p-2" aria-label="Close case detail"><X size={18} /></button></header><div className="flex overflow-x-auto border-b px-2" role="tablist">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} role="tab" aria-selected={tab === item} className={`shrink-0 border-b-2 px-3 py-3 text-[9px] font-bold ${tab === item ? 'border-moss text-moss' : 'border-transparent text-ink/45'}`}>{item}</button>)}</div><main className="min-h-0 flex-1 overflow-y-auto p-4">{section}</main><footer className="flex flex-wrap items-center justify-between gap-2 border-t bg-sand/50 p-3"><div className="flex gap-2"><button onClick={() => onOpenParcel?.(detail.parcel_id)} className="flex items-center gap-1 rounded-lg border bg-white px-3 py-2 text-[10px] font-bold"><MapPin size={12} /> Open Parcel</button>{detail.case_status === 'Field Verification Requested' && <button onClick={() => onStartInspection?.(detail)} className="rounded-lg bg-moss px-3 py-2 text-[10px] font-bold text-white">Start Inspection</button>}</div><button onClick={load} className="flex items-center gap-1 text-[10px] font-bold text-moss"><RefreshCw size={12} /> Refresh</button></footer></div>{lightbox && <button onClick={() => setLightbox(null)} className="fixed inset-0 z-[100] grid place-items-center bg-black/85 p-4" aria-label="Close case evidence viewer"><img src={lightbox.url} alt={lightbox.file_name} className="max-h-[90vh] max-w-full rounded-xl object-contain" /></button>}</div>
}
