import { useCallback, useEffect, useMemo, useState } from 'react'
import { AlertCircle, ClipboardCheck, Eye, ListFilter, LoaderCircle, RotateCcw } from 'lucide-react'

const empty = { level: '', taluka: '', verification: '', minScore: '0' }
const levels = ['Routine', 'Review Recommended', 'High Priority Review', 'Urgent Review']

export default function PriorityDashboard({ onView, onStartInspection }) {
  const [items, setItems] = useState(null)
  const [filters, setFilters] = useState(empty)
  const [error, setError] = useState('')
  const load = useCallback(() => {
    setItems(null); setError('')
    fetch('/api/priorities?limit=100').then((response) => { if (!response.ok) throw new Error(); return response.json() }).then((data) => setItems(data.items)).catch(() => setError('Priority queue is unavailable. Ensure the local backend is running.'))
  }, [])
  useEffect(() => { load() }, [load])
  const visible = useMemo(() => (items || []).filter((item) => (!filters.level || item.priority_level === filters.level) && (!filters.taluka || item.taluka === filters.taluka) && (!filters.verification || item.verification_status === filters.verification) && item.priority_score >= Number(filters.minScore || 0)), [items, filters])
  const summary = useMemo(() => ({ total: items?.length || 0, review: items?.filter((item) => item.priority_score >= 25).length || 0, high: items?.filter((item) => item.priority_level === 'High Priority Review').length || 0, urgent: items?.filter((item) => item.priority_level === 'Urgent Review').length || 0 }), [items])
  const update = (key, value) => setFilters((current) => ({ ...current, [key]: value }))

  if (error) return <div className="flex items-center justify-between gap-3 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><span className="flex items-center gap-2"><AlertCircle />{error}</span><button onClick={load} className="shrink-0 rounded-lg border border-rose-300 px-3 py-2 text-xs font-bold">Retry</button></div>
  if (!items) return <div className="grid min-h-[540px] place-items-center rounded-3xl bg-white text-sm text-ink/55"><span className="flex items-center gap-2"><LoaderCircle className="animate-spin" /> Loading inspection priority queue…</span></div>
  return <div className="space-y-4">
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[[summary.total, 'Total parcels'], [summary.review, 'Requires review'], [summary.high, 'High priority'], [summary.urgent, 'Urgent review']].map(([value, label]) => <div key={label} className="rounded-2xl border border-ink/10 bg-white p-4"><p className="font-display text-2xl font-extrabold">{value}</p><p className="text-[9px] font-bold uppercase tracking-wider text-ink/45">{label}</p></div>)}</div>
    <section className="rounded-2xl border border-ink/10 bg-white p-3 md:p-4"><div className="mb-3 flex items-center justify-between"><p className="flex items-center gap-2 text-xs font-extrabold"><ListFilter size={16} /> Queue filters</p><button onClick={() => setFilters(empty)} className="flex items-center gap-1 rounded-lg px-2 py-1 text-[10px] font-bold text-moss hover:bg-sand"><RotateCcw size={12} /> Clear filters</button></div><div className="grid grid-cols-2 gap-2 lg:grid-cols-4"><select aria-label="Priority level" value={filters.level} onChange={(event) => update('level', event.target.value)} className="h-10 rounded-xl border border-ink/15 px-3 text-xs"><option value="">All priority levels</option>{levels.map((level) => <option key={level}>{level}</option>)}</select><select aria-label="Priority taluka" value={filters.taluka} onChange={(event) => update('taluka', event.target.value)} className="h-10 rounded-xl border border-ink/15 px-3 text-xs"><option value="">All talukas</option>{['Ratnagiri', 'Chiplun', 'Sangameshwar'].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="Priority verification" value={filters.verification} onChange={(event) => update('verification', event.target.value)} className="h-10 rounded-xl border border-ink/15 px-3 text-xs"><option value="">All verification</option>{['Verified', 'Pending Verification', 'Requires Verification'].map((value) => <option key={value}>{value}</option>)}</select><label className="flex h-10 items-center gap-2 rounded-xl border border-ink/15 px-3 text-[10px] font-bold">Minimum score<input aria-label="Minimum score" type="number" min="0" max="100" value={filters.minScore} onChange={(event) => update('minScore', event.target.value)} className="min-w-0 flex-1 bg-transparent text-right text-xs outline-none" /></label></div></section>
    <section className="overflow-hidden rounded-2xl border border-ink/10 bg-white"><div className="flex items-center justify-between border-b border-ink/10 px-4 py-4"><div><h3 className="font-display text-base font-extrabold">Inspection Priority Queue</h3><p className="text-[10px] text-ink/45">Highest workflow priority first · {visible.length} shown</p></div><span className="rounded-full bg-sand px-3 py-1 text-[9px] font-bold">phase4-v1</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1040px] text-left text-xs"><thead className="bg-sand/70 text-[9px] uppercase tracking-wider text-ink/45"><tr>{['Rank', 'Parcel ID', 'Survey No.', 'Village', 'Change', 'Verification', 'Score', 'Level', 'Action'].map((heading) => <th key={heading} className="px-4 py-3">{heading}</th>)}</tr></thead><tbody className="divide-y divide-ink/8">{visible.map((item, index) => <tr key={item.parcel_id} className="hover:bg-sand/35"><td className="px-4 py-3 font-extrabold">{index + 1}</td><td className="px-4 py-3 font-bold">{item.parcel_id}</td><td className="px-4 py-3">{item.survey_number}</td><td className="px-4 py-3">{item.village}</td><td className="px-4 py-3">{item.change_percentage == null ? 'No analysis' : `${item.change_percentage}%`}</td><td className="px-4 py-3">{item.verification_status}</td><td className="px-4 py-3 font-display text-base font-extrabold">{item.priority_score}</td><td className="px-4 py-3"><span className="font-bold">{item.priority_level}</span></td><td className="px-4 py-3"><div className="flex gap-1"><button onClick={() => onView(item)} className="flex items-center gap-1 rounded-lg border border-ink/15 px-2.5 py-2 text-[10px] font-bold hover:bg-sand"><Eye size={13} /> View</button><button onClick={() => onStartInspection(item)} className="flex items-center gap-1 rounded-lg bg-ink px-2.5 py-2 text-[10px] font-bold text-white hover:bg-moss"><ClipboardCheck size={13} /> Inspect</button></div></td></tr>)}</tbody></table>{visible.length === 0 && <p className="p-8 text-center text-sm text-ink/45">No parcels match the queue filters.</p>}</div></section>
    <p className="rounded-xl bg-amber-50 p-3 text-[10px] leading-relaxed text-amber-900"><strong>Workflow decision support only:</strong> priority is based on synthetic parcel status and demo visual change. It is not a legal, ownership, or enforcement determination.</p>
  </div>
}
